<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/3/13
 * Time: 8:38
 */

namespace app\mobile\controller;


use app\AppFactory\AppFactory;
use app\AppFactory\Mobile\Application;
use app\BaseController;
use app\mobile\validate\VCommon;

class Common extends BaseController
{
    /**
     * @var Application
     */
    protected $app;
    protected $tokenArr;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->app = AppFactory::mobile();
    }


    /**
     * 验证扫设备盘点库存二维码，返回Token
     * @return array|string
     */
    public function checkScan()
    {
        $postData = input();
        try { $this->validate($postData, VCommon::class . '.stock');} catch (\Exception $e) { return returnValidate($e->getMessage());}
        return $this->app->checkScan($postData);
    }
}