<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2023/6/19
 * Time: 16:38
 */

namespace app\management\controller;


use app\AppFactory\Management\Application;
use think\exception\ValidateException;
use think\facade\Filesystem;

class Common extends AuthController
{
    /**
     * @var Application
     */
    protected $app;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $controller = strtolower(request()->controller());
        $action = strtolower(request()->action());
        if ($action == "add" || $action == "update") {
            $frequency = $controller . $action;
            $check = checkFrequency($frequency);
            if ($check !== true) {
                json(['state' => 300, 'msg' => $check])->send();
                die();
            }
        }
    }

    /**
     * 获取查询条件
     * @param array $params
     * @param boolean|int $is_string
     * @param array $condition
     * @return array
     */
    public function getWhere($params,$is_string = false,$condition = [])
    {
        $where = [];
        $conData = array_keys($condition);
        foreach ($params as $key => $value) {
            if ($key == "page" || $key == "pageNum" || $key == "token") continue;
            // 有特定的字段筛选项
            if ($condition && in_array($key,$conData)) {
                // like
                if ($condition[$key] == "like") {
                    $where[] = [$key,'like',"%$value%"];
                    continue;
                }
                // in
                if (strpos($value,",") || $condition[$key] == "in") {
                    $where[] = [$key,'in',$value];
                    continue;
                }
                // between
                if (strpos($value,"~") && $condition[$key] == "between") {
                    $this->between($key,$value,$where);
                    continue;
                }
            } else {
                if (is_numeric($value)) { // 数值型，等于
                    $where[] = [$key, "=", $value];
                    continue;
                }
                if (is_string($value)) { // 字符串
                    if (strpos($value, "~") !== false) { //  ~ 隔开的时间段，用BETWEEN
                        $this->between($key,$value,$where);
                        continue;
                    }
                    // ,隔开的字符串，用IN
                    if (strpos($value, ",") !== false) {
                        $where[] = [$key, 'in', $value];
                        continue;
                    }
                    // LIKE查询
                    $where[] = [$key, 'like', "%$value%"];
                    continue;
                }
            }
        }
        $where = array_merge($where,$this->authNodeWhere());
        // 转为SQL语句格式
        if ($is_string && $where) {
            $this->where2Str($where);
        }
        return $where;
    }

    /**
     * 数据权限筛选条件
     * @return array
     */
    public function authNodeWhere()
    {
        $where = [];
        // 数据权限
        if (isset($this->currentMenu['d_type']) && $this->currentMenu['d_type'] > 0) {
            // 数据权限，1：查所有，2：查部门，3：查本人，4：查所有下属，5：查直接下属，默认0，0为不开启数据权限验证
            // 优先级高的覆盖低的，优先级：1. 查所有 > 2. 查部门 > 3. 查本人 > 4. 查所有下属 > 5. 查直接下属
            // 查数据权限区域内的账号ID，根据不同的接口字段名附加账号ID筛选条件
            if ($this->currentMenu['d_type'] == 2 && $this->manager['ao_id'] > 0) {
                $where["ao_id"] = $this->manager['ao_id'];
            }
            if ($this->currentMenu['d_type'] >= 3) {
                $ids[] = $this->manager['manager_id'];
                $maxLevel = 999;
                if ($this->currentMenu['d_type'] == 5) $maxLevel = $this->manager['level'] + 1;
                if ($this->currentMenu['d_type'] > 3) {
                    $ids = $this->app->authManager->getChildIdList($this->manager['manager_id'], $ids, $this->manager['level'], $maxLevel);
                }
                $field = $this->app->authNode->getAuthDataFieldByUrl(request()->baseUrl());
                if ($field) $where[] = [$field,'in', $ids];
            }
        }
        return $where;
    }

    public function between($key,$value,&$where = [])
    {
        $value = explode("~", $value);
        if ((validateDate($value[0], 'Y-m-d') && validateDate($value[1], 'Y-m-d')) ||
            (validateDate($value[0], 'Y-m-d H:i:s') && validateDate($value[1], 'Y-m-d H:i:s'))) {
            $where[] = [$key, 'between', [strtotime($value[0]), strtotime($value[1])]];
        }
        if ((validateDate($value[0], 'H:i:s') && validateDate($value[1], 'H:i:s')) ||
            (validateDate($value[0], 'H:i') && validateDate($value[1], 'H:i'))) {
            $where[] = [$key, 'between', [HourMinuteSec2int($value[0]), HourMinuteSec2int($value[1])]];
        }
    }

    /**
     * 数组条件转SQL语句
     * @param $where
     */
    public function where2Str(&$where)
    {
        if (is_array($where)) {
            $strArr = [];
            foreach ($where as $wk => $wv) {
                $str = $wv[0];
                if (count($wv) > 2) {
                    if ($wv[1] == "like") {
                        $wv[2] = "'$wv[2]'";
                    }
                    if ($wv[1] == "between") {
                        $wv[2] = $wv[2][0] . " AND " . $wv[2][1];
                    }
                    if ($wv[1] == "in") {
                        $wv[2] = "($wv[2])";
                    }
                    $str .= " " . strtoupper($wv[1]) . " " . $wv[2];
                    $strArr[] = $str;
                    continue;
                }
                $str .= $wv[1] . " " . $wv[2];
                $strAr[] = $str;
            }
            $where = implode(" AND ", $strArr);
        }
    }

    /**
     * 获取当前登录的账号信息
     * @return array|string
     */
    public function getMineInfo()
    {
        if (isset($this->manager['password'])) unset($this->manager['password']);
        return returnState(200,"查询成功",$this->manager);
    }

    /**
     * 自定义文件夹上传文件
     * @return array|string
     */
    public function uploadFile()
    {
        $folder = input('folder');
        $file = request()->file("file");
        if (!$file) return returnState(100,'上传失败，file不能为空');
        if ($folder) {
            $folderPath = root_path("public/uploads/" . $folder);
            if (!is_dir($folderPath)) {
                @mkdir($folderPath);
                @chmod($folderPath,0777);
            }
        }
        try {
            validate(
                [
                    'file' => [
//                        "fileSize" => 2 * 1024 * 1024,
                        "fileExt" => "jpg,jpeg,gif,png,xls,xlsx,crt,csr,txt,pem,mp3,mp4,wav,aiff,aac,flac,ogg,m4a,amr,wma,pcm",
                    ],
                ],
                [
//                    "file.fileSize" => "文件太大",
                    "file.fileExt" => "不支持的上传文件类型",
                ]
            )->check(['file' => $file]);
            $diskName = env("fileSystem.diskName");     // 上传本地
//            $diskName = "aliyun";    // 上传OSS服务器
            $saveName = Filesystem::disk($diskName)->putFile($folder, $file);

            $path = Filesystem::getDiskConfig($diskName, 'url') . str_replace('\\', '/', $saveName);
            return returnState(200,'上传成功',$path);
        } catch (ValidateException $e) {
            return returnValidate($e->getMessage());
        }
    }

    /**
     * 获取当前账号的权限节点
     * @return array|string
     */
    public function getSelfRoleNode()
    {
        if ($this->manager['pid'] > 0) {
            $whereArn[] = ['role_id', 'in', $this->app->authManagerRole->getAuthManagerRoleColumn(['manager_id' => $this->manager['manager_id'], 'is_del' => 2], 'role_id')];
            $whereArn['is_del'] = 2;
            $where[] = ['node_id', 'in',$this->app->authRoleNode->getAuthRoleNodeColumn($whereArn,'node_id')];
        }
        $where['status'] = 1;
        $data = $this->app->authNode->getAuthNodeList($where,0,'node_id,pid,name,icon,url,desc,sort,type,is_auth,status','sort asc');
        $data = obj2arr($data);
        return returnData($data);
    }
}