<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2023/7/3
 * Time: 13:43
 */

namespace app\management\controller;


use app\AppFactory\AppFactory;
use app\AppFactory\Kernel\Model\Wx\WxOfficialModel;
use app\BaseController;
use think\captcha\facade\Captcha;
use think\facade\Lang;
use think\facade\Session;

class Login extends BaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Headers: token,Origin, X-Requested-With, Content-Type, Accept");
        header('Access-Control-Allow-Methods: POST,GET');
    }

    protected $validatePath = 'app\management\validate\VLogin.';

    /**
     * 获取验证码
     * @return array|string
     */
    public function getCaptcha()
    {
//        return returnState(200,Lang::get('query_success'));
        try {
            $uniqid = uniqid(rand(00000, 99999));
            $rs = Captcha::create();
            $base64_image = "data:image/png;base64," . base64_encode($rs->getData());
            $key = session("captcha.key");
            cache("management_" . $uniqid, $key);
            $data = [
                "uniqid" => $uniqid,
                "content" => $base64_image,
            ];
            return returnState(200, Lang::get("captcha.get_success"), $data);
        } catch (\Exception $e) {
            actionException($e,1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 登录
     * @return array|string
     */
    public function login()
    {
        try {
            $data = input();
            try {
                $this->validate($data, $this->validatePath . 'login');
            } catch (\Exception $e) {
                return returnValidate(Lang::get($e->getMessage()));
            }
            $key = cache("management_" . $data['uniqid']);
            if ($key && password_verify(mb_strtolower($data['code'], 'UTF-8'), $key)) {
                cache("management_" . $data['uniqid'], null);
                $app = AppFactory::management();
                $result = $app->login->login($data);
                return $result;
            } else {
                return returnValidate(Lang::get("captcha.code_error"));
            }
        } catch (\Exception $e) {
            actionException($e,1);
            return returnTryCatch(Lang::get($e->getMessage()));
        }
    }

    /**
     * 退出登录状态
     * @return array|string
     */
    public function logout()
    {
        Session::clear();
        $data = Session::get("manager");
        if (!$data){
            return returnState(200,Lang::get("VLogin.logout_success"));
        }
        return returnState(100,Lang::get("VLogin.logout_fail"));
    }

    /**
     * 获取微信登录链接
     * @return array|\think\response\Json
     */
    public function getWxLoginUrl()
    {
        $postData = input();
        return AppFactory::management()->login->getWxLoginUrl($postData);
    }

    /**
     * 监听微信登录状态
     * @return array|\think\response\Json
     */
    public function checkWxLoginStatus()
    {
        $postData = input();
        return AppFactory::management()->login->checkWxLoginStatus($postData);
    }
}