<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2023/6/20
 * Time: 15:00
 */

namespace app\management\controller;


use app\AppFactory\AppFactory;
use app\AppFactory\Kernel\Model\Auth\AuthManagerModel;
use app\AppFactory\Kernel\Model\Earth\EarthCitiesModel;
use app\AppFactory\Kernel\Model\Earth\EarthRegionsModel;
use app\AppFactory\Kernel\Model\Earth\EarthStatesModel;
use app\AppFactory\Kernel\Support\TDESUtil;
use app\AppFactory\Management\Application;
use app\BaseController;
use think\facade\Cache;
use think\facade\Config;
use think\facade\Db;

class Test extends BaseController
{
    public function testTemplateView()
    {
        $fields = '[{"key":"loop","options":"bars","type":"SELECT","display":{"en_US":"Image Loop Mode",
"ja_JP": "イメージループモード","zh_CN":"轮播方式","zh_TW":"輪播方式"}}]';
        $plugin = [
            "plugin_name" => "广告插件",
            "display_name" => '{"zh-cn":"广告插件","en":"advertise plugin"}',
            "type" => 1,
            "fields" => json2arr($fields)
        ];
        $plugin_data = [
            "layout_id" => 1,
            "plugin_id" => 1,
            "height" => 300,
            "width" => 500,
            "left" => 20,
            "top" => 30,
            "plugin" => $plugin,
        ];
        dump($plugin_data);
        $data = [
            "name" => "测试视图",
            "template_id" => "1",
            "height" => 1920,
            "width" => 1080,
            "plugin_data" => json_encode($plugin_data,256+64),
        ];
        dump($data);
        return arr2json($data);

    }
    public function makeStreet()
    {

        $province = EarthStatesModel::getList(['country_id' => 44])->toArray();
        $state_ids = array_column($province,'id');
//        $state_ids = array_search(,$province);
//        dump($state_ids);
//        dump($state_ids);
        $where[] = ['state_id' , 'in',$state_ids];
        dump($where);
        $city = EarthCitiesModel::getList($where)->toArray();
        dump($city);
//        $region = EarthRegionsModel::getList([''])
        die();


        foreach ($province as $pk => $pv) {
            dump($pv);
            $pro = Db::name("city")->where(['city_title' => $pv['cname']])->find();
            dump($pro);
            echo "<br>";
        }
    }
    public function testWeek()
    {
        $week = date("w");
        dump($week);

    }
    public function testDateTime()
    {
        $time = 1688109246;
        dump($time);
        dump(date("Y-m-d H:i:s",$time));
        dump(date("Y-m-d 23:59:59",$time));
        dump(strtotime(date("Y-m-d 23:59:59",$time)));
    }
    public function testArrValue()
    {
        $data = [
            "door" => 1,
            "lock" => 2,
            "button" => 3,
        ];
        dump(array_values($data));
        dump(implode("",array_values($data)));
    }
    /**
     * @var Application
     */
    protected $app;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $manager = AuthManagerModel::getFind(['manager_id' => 1]);
        $this->app = AppFactory::management($manager->getData());
    }

    public function getToken()
    {
        $manager = AuthManagerModel::getFind(['manager_id' => 5]);
        session("manager",$manager);
        $token_arr = [
            "session_id" => session_id(),
            "manager_id" => $manager['manager_id'],
            "timeout" => time(),
        ];
        $key = Config::get("app.salt");
        $token = TDESUtil::encrypt(json_encode($token_arr),$key);
        dump($token);
    }

    public function checkF()
    {
        $controller = request()->controller();
        $action = request()->controller();
    }

    public function qrCode()
    {
        $url = "http://www.baidu.com";
        $app = AppFactory::management();
        $config = [
            "folder" => "enQr",
            "name" => "en_2",
//            "text" => "",
            "logoPath" => true,
            "size" => "500",
            "margin" => 5,
            "resizeToWidth" => 80,
        ];
        $qr = $app->warehouseOrder->makeQr($url,$config);
        dump($qr);
    }

    public function getChildIds()
    {
        $manager = AuthManagerModel::getFind(['manager_id' => 1]);
        $app = AppFactory::management($manager->getData());
        echo "time1:",date("Y-m-d H:i:s"),"<br>";
        $ids = $app->authManager->getChildIdList($manager['manager_id'],[],$manager['level'],3);
        echo "time2:",date("Y-m-d H:i:s"),"<br>";
        $parent = $app->authManager->getParentIdList($manager['pid']);
        dump($parent);

    }

//    public function validateTime()
//    {
//         md5("dkm" . Config::get("app.salt"));
//        Url::bind("test/validateTime");
//        $time = "10:00";
//        dump(validateDate($time,"i:s"));
//        $int = "3665";
//        dump(Int2HourMinuteSec($int,3));
//    }
}