<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2023/6/20
 * Time: 15:00
 */

namespace app\management\controller;


use app\AppFactory\AppFactory;
use app\AppFactory\Kernel\Model\Auth\AuthManagerModel;
use app\AppFactory\Kernel\Support\TDESUtil;
use app\AppFactory\Management\Application;
use app\BaseController;
use think\facade\Cache;
use think\facade\Config;

class Test extends BaseController
{
    public function testWeek()
    {
        $week = date("w");
        dump($week);

    }
    public function testDateTime()
    {
        $time = 1688109246;
        dump($time);
        dump(date("Y-m-d H:i:s",$time));
        dump(date("Y-m-d 23:59:59",$time));
        dump(strtotime(date("Y-m-d 23:59:59",$time)));
    }
    public function testArrValue()
    {
        $data = [
            "door" => 1,
            "lock" => 2,
            "button" => 3,
        ];
        dump(array_values($data));
        dump(implode("",array_values($data)));
    }
    /**
     * @var Application
     */
    protected $app;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $manager = AuthManagerModel::getFind(['manager_id' => 1]);
        $this->app = AppFactory::management($manager->getData());
    }

    public function getToken()
    {
        $manager = AuthManagerModel::getFind(['manager_id' => 1]);
        session("manager",$manager);
        $token_arr = [
            "session_id" => session_id(),
            "manager_id" => $manager['manager_id'],
            "timeout" => time(),
        ];
        $key = Config::get("app.salt");
        $token = TDESUtil::encrypt(json_encode($token_arr),$key);
        dump($token);
    }

    public function testEn()
    {
        $postData = '{"receiver":1,"total_quantity":15,"contacts":"猫哥","mobile":"15269874123","province_id":19,"city_id":313,"area_id":3218,"address":"102号街道","logistics_no":"999664544","remark":"我是备注信息","wgList":[{"wg_id":"0","goods_id":13,"wg_name":"煲仔饭测试","wg_pic":"/uploads/goods_img/20230708/41e9eeda62bfc06ddccd42980fa9c165.jpg","bar_code":"123456789","batch_number":"123456789","manufacture_time":1689120000,"cost_price":"12.00","retail_price":"16.00","sell_by_date":"15","before_stock":"0","quantity":"15"}]}';
        $postData = json2arr($postData);
        dump($postData);
        $result = $this->app->warehouseOrder->addWarehouseOrder($postData);
        dump($result->getData());
    }

    public function testCmd()
    {
        $data['terminal_no'] = "test0001";
        $send = [
            "hardwareNumber" => "lock0001",
            "cmd" => "unlock",
            "sendType" => "manager",
        ];
        $app = AppFactory::gatewayWorker();
        $result = $app->sendTerminal->cmd($data['terminal_no'],$send,"controlLock");
        dump($result);
    }

    public function testSaveNotice()
    {
        $notice = [
            "manager_id" => 4,
            "list" => [
                [
                    "notice_type" => 1,
                    "status" => 2,
                ],
                [
                    "notice_type" => 2,
                    "status" => 1,
                ],
                [
                    "notice_type" => 3,
                    "status" => 2,
                ],
                [
                    "notice_type" => 4,
                    "status" => 1,
                ],
                [
                    "notice_type" => 5,
                    "status" => 1,
                ],
                [
                    "notice_type" => 6,
                    "status" => 2,
                ],
                [
                    "notice_type" => 7,
                    "status" => 1,
                ],
                [
                    "notice_type" => 8,
                    "status" => 2,
                ],
                [
                    "notice_type" => 9,
                    "status" => 1,
                ],
                [
                    "notice_type" => 10,
                    "status" => 1,
                ],
                [
                    "notice_type" => 11,
                    "status" => 2,
                ],
                [
                    "notice_type" => 12,
                    "status" => 2,
                ],
            ],
        ];
        dump(json_encode($notice));
    }

    public function testStoreAdd()
    {
        $postData = [
            "store_name" => "测试门店1",
            "pic" => "123123123123",
            "store_manager" => 2,
            "province_id" => 19,
            "city_id" => 19,
            "area_id" => 19,
            "address" => "测试详细地址",
            "contacts" => "测试2",
            "mobile" => "13222222222",
            "store_type" => "1,2",
            "terminal_no" => "test0001",
            "status" => 1,
            "sc" => json_encode([
                [
                    "manager_id" => 4,
                    "nickname" => "测试2-1",
                    "mobile" => "13333333333",
                    "clerk_type" => 1,
                ],
                [
                    "manager_id" => 5,
                    "nickname" => "测试2-2",
                    "mobile" => "13444444444",
                    "clerk_type" => 2,
                ],
            ],JSON_UNESCAPED_UNICODE + JSON_UNESCAPED_SLASHES),
            "sh" => json_encode([
                [
                    "hardware_name" => "测试电子锁1",
                    "hardware_number" => "lock001",
                    "hardware_type" => 1,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "测试密码锁1",
                    "hardware_number" => "lock002",
                    "hardware_type" => 2,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "UPS1",
                    "hardware_number" => "ups0001",
                    "hardware_type" => 3,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "测试拾音器1",
                    "hardware_number" => "pickup001",
                    "hardware_type" => 4,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "测试扬声器1",
                    "hardware_number" => "speaker001",
                    "hardware_type" => 5,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "测试反扫器1",
                    "hardware_number" => "scan001",
                    "hardware_type" => 6,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "测试小票机1",
                    "hardware_number" => "print001",
                    "hardware_type" => 7,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "测试摄像头1",
                    "hardware_number" => "camera001",
                    "hardware_type" => 8,
                    "status" => 1,
                ],
                [
                    "hardware_name" => "测试摄像头2",
                    "hardware_number" => "camera002",
                    "hardware_type" => 8,
                    "status" => 1,
                ],
            ],JSON_UNESCAPED_UNICODE + JSON_UNESCAPED_SLASHES),
            "sot" => json_encode([
                [
                    "start_time" => "00:00:00",
                    "end_time" => "08:00:00",
                ],
                [
                    "start_time" => "21:00:00",
                    "end_time" => "23:59:59",
                ],
            ],JSON_UNESCAPED_UNICODE + JSON_UNESCAPED_SLASHES),
            "sp" => json_encode([
                "pay_type" => "1,2,3,4,5",
                "auto_refund" => 1,
            ],JSON_UNESCAPED_UNICODE + JSON_UNESCAPED_SLASHES),
            "ss" => json_encode([
                [
                    "shelves_number" => "01",
                    "goods_id" => "",
                    "wg_id" => "",
                    "goods_name" => "",
                    "goods_c_id" => "",
                    "goods_c_name" => "",
                    "goods_pic" => "",
                    "cost_price" => "",
                    "retail_price" => "",
                    "stock" => "",
                    "batch_number" => "",
                    "manufacture_time" => "",
                    "sell_by_date" => "",
                ],
                [
                    "shelves_number" => "02",
                    "goods_id" => "",
                    "wg_id" => "",
                    "goods_name" => "",
                    "goods_c_id" => "",
                    "goods_c_name" => "",
                    "goods_pic" => "",
                    "cost_price" => "",
                    "retail_price" => "",
                    "stock" => "",
                    "batch_number" => "",
                    "manufacture_time" => "",
                    "sell_by_date" => "",
                ],
            ],JSON_UNESCAPED_UNICODE + JSON_UNESCAPED_SLASHES),
        ];
        $postData = json_encode($postData,JSON_UNESCAPED_SLASHES + JSON_UNESCAPED_UNICODE);
        dump($postData);
    }

    public function checkF()
    {
        $controller = request()->controller();
        $action = request()->controller();
    }

    public function qrCode()
    {
        $url = "http://www.baidu.com";
        $app = AppFactory::management();
        $config = [
            "folder" => "enQr",
            "name" => "en_2",
//            "text" => "",
            "logoPath" => true,
            "size" => "500",
            "margin" => 5,
            "resizeToWidth" => 80,
        ];
        $qr = $app->warehouseOrder->makeQr($url,$config);
        dump($qr);
    }

    public function getChildIds()
    {
        $manager = AuthManagerModel::getFind(['manager_id' => 1]);
        $app = AppFactory::management($manager->getData());
        echo "time1:",date("Y-m-d H:i:s"),"<br>";
        $ids = $app->authManager->getChildIdList($manager['manager_id'],[],$manager['level'],3);
        echo "time2:",date("Y-m-d H:i:s"),"<br>";
        $parent = $app->authManager->getParentIdList($manager['pid']);
        dump($parent);

    }

//    public function validateTime()
//    {
//         md5("dkm" . Config::get("app.salt"));
//        Url::bind("test/validateTime");
//        $time = "10:00";
//        dump(validateDate($time,"i:s"));
//        $int = "3665";
//        dump(Int2HourMinuteSec($int,3));
//    }
}