<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/8/3
 * Time: 10:24
 */

namespace app\machine\controller;

use app\AppFactory\AppFactory;
use app\AppFactory\Machine\Application;
use app\machine\validate\VHotel;

class Hotel extends Common
{
    protected $validatePath = VHotel::class . ".";
    protected $config;
    /**
     * @var Application
     */
    protected $app;

    /**
     * 初始化
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $postData = input();
        $postData = json2arr($postData);
        actionLog($postData,'接收到的数据');
        $action = $this->request->action();
        $reflection = new \ReflectionClass(__CLASS__);
        $methods = $reflection->getMethods();
        $methodNames = array_map(function ($method) {
            return $method->getName();
        },$methods);
        if (!in_array($action,$methodNames)) {
            returnState(300,lang("error_api"))->send();
            die();
        }
        try {
            $this->validate($postData,$this->validatePath . $action);
        } catch (\Exception $e) {
            returnTryCatch(lang($e->getMessage()))->send();
            die();
        }
        $frequency = checkFrequency($action);
        if ($frequency !== true) {
            returnState(300,lang($frequency))->send();
            die();
        }
        $mac = $this->request->header("mac");
        $this->config = [
            "machine_id" => $postData['machine_id'],
            "data" => $postData,
            "mac" => $mac,
        ];
        $this->app = AppFactory::machine($this->config);
        if ($this->app->hotel->checkSign($postData) !== true) {
            @cache($postData['machine_id'] . ".signKey",null);
            returnTryCatch(lang(lang("check_sign_fail")))->send();
            die();
        }
    }

    /**
     * 获取携程套餐商品列表
     * @return array|\think\response\Json
     */
    public function getTripMultiple()
    {
        return $this->app->hotel->getTripMultiple();
    }

    /**
     * 获取携程城市列表
     * @return array|\think\response\Json
     */
    public function getTripCity()
    {
        return $this->app->hotel->getCity();
    }

    /**
     * 根据城市ID获取酒店列表
     * @return array|\think\response\Json
     */
    public function getList()
    {
        return $this->app->hotel->getList();
    }

    /**
     * 获取酒店详情
     * @return array|\think\response\Json
     */
    public function getDetails()
    {
        return $this->app->hotel->getDetails();
    }

    /**
     * 获取酒店房间列表
     * @return array|\think\response\Json
     */
    public function getRoomList()
    {
        return $this->app->hotel->getRoomList();
    }

    /**
     * 订单上报酒店
     * @return array|bool|string|\think\response\Json
     */
    public function subHotel()
    {
        return $this->app->hotel->subHotel();
    }
}