<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/8/3
 * Time: 10:24
 */

namespace app\machine\controller;

use app\AppFactory\AppFactory;
use app\AppFactory\Machine\Application;
use think\facade\Lang;

class Hotel extends Common
{
    protected $validatePath = 'app\machine\validate\VHotel.';
    protected $config;
    /**
     * @var Application
     */
    protected $app;

    /**
     * 初始化
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $postData = input();
        $postData = json2arr($postData);
        actionLog($postData,'接收到的数据');
        $action = $this->request->action();
        try {
            $this->validate($postData,$this->validatePath . $action);
        } catch (\Exception $e) {
            die(json_encode(['state' => 300, 'msg' => Lang::get($e->getMessage())],320));
        }
        $frequency = checkFrequency($action);
        if ($frequency !== true) {
            $frequency = obj2arr($frequency);
            die(json_encode($frequency,320));
        }
        $this->config = [
            "machine_id" => $postData['machine_id'],
            "data" => $postData,
        ];
        $this->app = AppFactory::machine($this->config);
        if ($this->app->hotel->checkSign($postData) !== true) {
            @cache($postData['machine_id'] . ".signKey",null);
            die(json_encode(["state" => 100, "msg" => Lang::get("check_sign_fail")], 320));
        }
    }

    /**
     * 获取携程城市列表
     * @return array|\think\response\Json
     */
    public function getTripCity()
    {
        return $this->app->hotel->getCity();
    }

    /**
     * 根据城市ID获取酒店列表
     * @return array|\think\response\Json
     */
    public function getList()
    {
        return $this->app->hotel->getList();
    }

    /**
     * 获取酒店详情
     * @return array|\think\response\Json
     */
    public function getDetailsList()
    {
        return $this->app->hotel->getDetailsList();
    }

    /**
     * 获取酒店房间列表
     * @return array|\think\response\Json
     */
    public function getRoomList()
    {
        return $this->app->hotel->getRoomList();
    }
}