<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/1/22
 * Time: 20:18
 */

namespace app\machine\controller;
use app\AppFactory\AppFactory;
use app\AppFactory\Machine\Application;
use think\facade\Lang;

/**
 * 接收设备终端上报或请求
 * @package app\machine\controller
 */
class Receive extends Common
{
    protected $validatePath = 'app\machine\validate\VReceive.';
    protected $config;
    /**
     * @var Application
     */
    protected $app;


    /**
     * 初始化
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $postData = input();
        $postData = json2arr($postData);
        actionLog($postData,'接收到的数据');
        $action = $this->request->action();
        try { $this->validate($postData,$this->validatePath . $action);}
        catch (\Exception $e) { die(json_encode(['state' => 300, 'msg' => Lang::get($e->getMessage())],320));}
        $frequency = checkFrequency($action);
        if ($frequency !== true) {
            $frequency = obj2arr($frequency);
            die(json_encode($frequency,320));
        }
        $this->key = cache($postData['machine_id'] . ".signKey");
        $this->config = [
            "machine_id" => $postData['machine_id'],
            "key" => $this->key,
            "data" => $postData,
        ];
        $this->app = AppFactory::machine($this->config);
        if ($this->app->api->checkSign($postData) !== true)
            die(json_encode(["state" => 100,"msg" => Lang::get("check_sign_fail")],320));

    }

    /**
     * 登录
     * @return array|string
     */
    public function login()
    {
        return $this->app->api->login();
    }

    /**
     * 退出登录
     * @return array|string
     */
    public function logout()
    {
        return $this->app->api->logout();
    }

    /**
     * 获取系统配置信息
     * @return array|string
     */
    public function getSystemInfo()
    {
        return $this->app->api->systemInfo();
    }

    /**
     * 获取设备主体信息
     * @return array|string
     */
    public function getMachine()
    {
        return $this->app->api->machine();
    }

    /**
     * 获取设备货道信息
     * @return array|string
     */
    public function getMachineChannel()
    {
        return $this->app->api->machineChannel();
    }

    /**
     * 获取设备商品信息
     * @return array|string
     */
    public function getMachineGoods()
    {
        return $this->app->api->machineGoods();
    }

    /**
     * 获取设备其他信息
     * @return array|string
     */
    public function getMachineInfo()
    {
        return $this->app->api->machineInfo();
    }

    /**
     * 获取设备营业配置信息
     * @return array|\think\response\Json
     */
    public function getMachineOnOff()
    {
        return $this->app->api->machineOnOff();
    }

    /**
     * 获取设备配置信息
     * @return array|string
     */
    public function getMachineConfig()
    {
        return $this->app->api->machineConfig();
    }

    /**
     * 获取设备帮助信息
     * @return array|string
     */
    public function getMachineHelp()
    {
        return $this->app->api->machineHelp();
    }

    /**
     * 获取设备屏幕首页视图模板
     * @return array|string
     */
    public function getMachineView()
    {
        return $this->app->api->machineView();
    }

    /**
     * 获取最新一条设备软件更新信息
     * @return array|string
     */
    public function getMachineVersionPlan()
    {
        return $this->app->api->machineVersionPlan();
    }

    /**
     * 获取商品信息
     * @return array|string
     */
    public function getGoods()
    {
        return $this->app->api->goods();
    }

    /**
     * 获取指定商品信息
     * @return array|string
     */
    public function getGoodsFind()
    {
        return $this->app->api->goodsFind();
    }

    /**
     * 获取广告
     * @return array|string
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     */
    public function getAdv()
    {
        return $this->app->api->adv();
    }

    /**
     * 上报播放广告
     * @return array|string
     */
    public function playAdv()
    {
        return $this->app->api->playAdv();
    }

    /**
     * 上报购物车
     * @return array|string
     * @throws \Exception
     */
    public function subCar()
    {
        return $this->app->api->subCar();
    }

    /**
     * 提交货道信息
     * @return array|string
     */
    public function subChannel()
    {
        return $this->app->api->subChannel();
    }

    /**
     * 提交设备备用商品信息
     * @return array|string
     */
    public function subMachineGoods()
    {
        return $this->app->api->subMachineGoods();
    }

    /**
     * 货道补货
     * @return mixed
     */
    public function replenishment()
    {
        return $this->app->api->channelReplenishment();
    }

    /**
     * 修改货道商品
     * @return array|string
     */
    public function changeChannelGoods()
    {
        return $this->app->api->changeChannelGoods();
    }

    /**
     * 上传销售媒体文件
     * @return array|string
     */
    public function uploadMedia()
    {
        return $this->app->api->uploadFiles();
    }

    /**
     * 获取库存盘点二维码
     * @return array|string
     */
    public function getCheckStockImg()
    {
        return $this->app->api->checkStockQrCode();
    }

    /**
     * 获取设备优惠券活动列表
     * @return array|string
     */
    public function getCouponList()
    {
        return $this->app->activity->getByMachine();
    }

    /**
     * 使用优惠券码获取优惠券活动信息
     * @return array|string
     */
    public function getCoupon()
    {
        return $this->app->activity->getByCode();
    }

    /**
     * 通过设备获取取货码列表
     * @return array|string
     */
    public function getPickList()
    {
        return $this->app->activity->getApByMachine();
    }

    /**
     * 输入取货码获取取货码信息
     * @return array|string
     */
    public function getPick()
    {
        return $this->app->activity->getApByCode();
    }

    /**
     * 获取抽奖活动列表
     * @return array|string
     */
    public function getLotteryList()
    {
        return $this->app->activity->getAlByMachine();
    }

    /**
     * 生成抽奖活动订单
     * @return array|string
     */
    public function getLotteryOrder()
    {
        return $this->app->activity->lotteryOrder();
    }

    /**
     * 执行抽奖结果
     * @return array|string
     * @throws \Exception
     */
    public function getLuckyDraw()
    {
        return $this->app->activity->luckyDrawResult();
    }

    /**
     * 抽奖订单出货
     * @return array|string
     * @throws \Exception
     */
    public function getLotteryOutGoods()
    {
        return $this->app->activity->lotteryOutGoods();
    }

    /**
     * 获取设备满减满送活动信息
     * @return array|string
     */
    public function getFd()
    {
        return $this->app->activity->getFdByMachine();
    }

    /**
     * 使用提货码
     * @return array|\think\response\Json
     */
    public function usePickCode()
    {
        return $this->app->activity->usePickCode();
    }

    /**
     * 订单使用满减满送活动
     * @return mixed
     */
    public function useFd()
    {
        return $this->app->activity->useFd();
    }

    /**
     * 订单使用优惠券
     * @return array|\think\response\Json
     */
    public function useCoupon()
    {
        return $this->app->activity->useCoupon();
    }

    /**
     * 获取设备公网IP
     * @return array|string
     */
    public function getIp()
    {
        return $this->app->api->ip();
    }

    /**
     * 未取事件上报
     * @return array|bool|string
     */
    public function unclaimed()
    {
        return $this->app->saleOrders->subUnclaimed();
    }

    /**
     * 重置出厂设置
     * @return mixed
     */
    public function resetMachine()
    {
        return $this->app->api->reset();
    }
}