<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/1/22
 * Time: 20:18
 */

namespace app\machine\controller;
use app\AppFactory\AppFactory;
use app\AppFactory\Machine\Application;
use think\facade\Lang;

/**
 * 接收设备终端上报或请求
 * @package app\machine\controller
 */
class Receive extends Common
{
    protected $type = [
        1 => "query",          // 查询
        2 => "set",             // 设置
        3 => "report",         // 上报
    ];

    protected $action = [
        1 => "machine",
        12 => "",
        13 => "",
        14 => "",
        15 => "",
    ];

    protected $validatePath = 'app\machine\validate\VReceive.';
    protected $config;
    /**
     * @var Application
     */
    protected $app;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $postData = input();
//        $action = $this->request->action();
        try { $this->validate($postData,$this->validatePath);} catch (\Exception $e) { die(json_encode(['state' => 300, 'msg' => $e->getMessage()],320));}
        $this->config = [
            "machine_id" => $postData['machine_id'],
            "key" => $this->key,
            "data" => $postData,
        ];
        $this->app = AppFactory::machine($this->config);
        if ($this->app->api->checkSign($postData) !== true)
            die(json_encode(["state" => 100,"msg" => Lang::get("check_sign_fail")],320));

    }
    
    public function getMachine()
    {
        return $this->app->api->machine();
    }

    public function getMachineChannel()
    {
        return $this->app->api->machineChannel();
    }

    public function getMachineGoods()
    {
        return $this->app->api->machineGoods();
    }

    public function getMachineInfo()
    {
        return $this->app->api->machineInfo();
    }

    public function getMachineConfig()
    {
        return $this->app->api->machineConfig();
    }

    public function getMachineHelp()
    {
        return $this->app->api->machineHelp();
    }

    public function getGoods()
    {
        return $this->app->api->goods();
    }

    public function getAdv()
    {
        return $this->app->api->adv();
    }

    public function subCar()
    {
        return $this->app->api->subCar();
    }
}