<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/1/22
 * Time: 20:18
 */

namespace app\machine\controller;

use app\AppFactory\AppFactory;
use app\AppFactory\Kernel\Traits\Machine\SimSignalLogTrait;
use app\AppFactory\Machine\Application;
use app\AppFactory\RabbitMq\MqProducer;
use think\db\exception\DataNotFoundException;
use think\db\exception\DbException;
use think\db\exception\ModelNotFoundException;
use think\facade\Lang;
use think\View;

/**
 * 接收设备终端上报或请求
 * @package app\machine\controller
 */
class Receive extends Common
{
    use SimSignalLogTrait;

    protected $validatePath = 'app\machine\validate\VReceive.';
    protected $config;
    /**
     * @var Application
     */
    protected $app;

    protected $noCheckApi = [
        "logoutH5",
        'test',
    ];

    /**
     * 初始化
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try {
            $postData = input();
            $postData = json2arr($postData);
            actionLog($postData, '接收到的数据');
            $action = $this->request->action();
            $reflection = new \ReflectionClass(__CLASS__);
            $methods = $reflection->getMethods();
            $methodNames = array_map(function ($method) {
                return $method->getName();
            }, $methods);
            if (!in_array($action, $methodNames)) {
                returnState(300, lang("error_api"))->send();
                die();
            }

            if (!env('CglPay.is_test')) {
                $this->validate($postData, $this->validatePath . $action);
            }
            $frequency = checkFrequency($action, 1);
            if ($frequency !== true) {
                $frequency = obj2arr($frequency);
                returnState(300, $frequency)->send();
                die();
            }
            $mac = $this->request->header("mac");
            $this->config = [
                "machine_id" => $postData['machine_id'],
                "data" => $postData,
                "mac" => $mac
            ];
            $this->app = AppFactory::machine($this->config);
            if (!env('CglPay.is_test')) {
                if (!in_array($action, $this->noCheckApi) && $this->app->api->checkSign($postData) !== true) {
                    @cache($postData['machine_id'] . ".signKey", null);
                    returnState(100, Lang::get("check_sign_fail"))->send();
                    die();
                }
            }
        } catch (\Exception $e) {
            returnState(300, Lang::get($e->getMessage()))->send();
            die();
        }
    }

    /**
     * 登录
     * @return array|string
     */
    public function login()
    {
        try {
            return $this->app->api->login();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 微信登录
     * @return array|string
     */
    public function wxLogin()
    {
        try {
            return $this->app->api->wxLoginQrCode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 退出登录
     * @return array|string
     */
    public function logout()
    {
        try {
            return $this->app->api->logout();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取系统配置信息
     * @return array|string
     */
    public function getSystemInfo()
    {
        try {
            return $this->app->api->systemInfo();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备主体信息
     * @return array|string
     */
    public function getMachine()
    {
        try {
            return $this->app->api->machine();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备主体信息多语言数据
     * @return array|\think\response\Json
     */
    public function getMachineLangList()
    {
        try {
            return $this->app->api->machineLang();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备货道信息
     * @return array|string
     */
    public function getMachineChannel()
    {
        try {
            return $this->app->api->machineChannel();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备商品信息
     * @return array|string
     */
    public function getMachineGoods()
    {
        try {
            return $this->app->api->machineGoods();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备其他信息
     * @return array|string
     */
    public function getMachineInfo()
    {
        try {
            return $this->app->api->machineInfo();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备营业配置信息
     * @return array|\think\response\Json
     */
    public function getMachineOnOff()
    {
        try {
            return $this->app->api->machineOnOff();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备配置信息
     * @return array|string
     */
    public function getMachineConfig()
    {
        try {
            return $this->app->api->machineConfig();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备配置多语言数据
     * @return array|\think\response\Json
     */
    public function getMachineConfigLangList()
    {
        try {
            return $this->app->api->machineConfigLang();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备帮助信息
     * @return array|string
     */
    public function getMachineHelp()
    {
        try {
            return $this->app->api->machineHelp();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备屏幕首页视图模板
     * @return array|string
     */
    public function getMachineView()
    {
        try {
            return $this->app->api->machineView();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备屏幕视图模板列表，兼容包含首页视图模板
     * @return array|string
     */
    public function getMachineViewList()
    {
        try {
            return $this->app->api->machineViewList();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取最新一条设备软件更新信息
     * @return array|string
     */
    public function getMachineVersionPlan()
    {
        try {
            return $this->app->api->machineVersionPlan();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 上报设备软件更新下载进度
     * @return array|\think\response\Json
     */
    public function reportMachineVersionDownload()
    {
        try {
            return $this->app->api->machineVersionDownload();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取商品信息
     * @return array|string
     */
    public function getGoods()
    {
        try {
            return $this->app->api->goods();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取指定商品信息
     * @return array|string
     */
    public function getGoodsFind()
    {
        try {
            return $this->app->api->goodsFind();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取广告
     * @return array|string
     */
    public function getAdv()
    {
        try {
            return $this->app->api->adv();
        } catch (DataNotFoundException $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        } catch (ModelNotFoundException $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        } catch (DbException $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 上报播放广告
     * @return array|string
     */
    public function playAdv()
    {
        try {
            return $this->app->api->playAdv();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 上报广告素材下载百分比
     * @return array|\think\response\Json
     */
    public function reportAdvDownload()
    {
        try {
            return $this->app->api->reportAdvDownLoad();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 上报购物车
     * @return array|string
     * @throws \Exception
     */
    public function subCar()
    {
        try {
            return $this->app->api->subCar();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 提交货道信息
     * @return array|string
     */
    public function subChannel()
    {
        try {
            return $this->app->api->subChannel();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 提交设备备用商品信息
     * @return array|string
     */
    public function subMachineGoods()
    {
        try {
            return $this->app->api->subMachineGoods();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 货道补货
     * @return mixed
     */
    public function replenishment()
    {
        try {
            return $this->app->api->channelReplenishment();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 修改货道商品
     * @return array|string
     */
    public function changeChannelGoods()
    {
        try {
            return $this->app->api->changeChannelGoods();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 上传销售媒体文件
     * @return array|string
     */
    public function uploadMedia()
    {
        try {
            return $this->app->api->uploadFiles();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取库存盘点二维码
     * @return array|string
     */
    public function getCheckStockImg()
    {
        try {
            return $this->app->api->checkStockQrCode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备优惠券活动列表
     * @return array|string
     */
    public function getCouponList()
    {
        try {
            return $this->app->activity->getByMachine();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 使用优惠券码获取优惠券活动信息
     * @return array|string
     */
    public function getCoupon()
    {
        try {
            return $this->app->activity->getByCode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 通过设备获取取货码列表
     * @return array|string
     */
    public function getPickList()
    {
        try {
            return $this->app->activity->getApByMachine();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 输入取货码获取取货码信息
     * @return array|string
     */
    public function getPick()
    {
        try {
            return $this->app->activity->getApByCode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取抽奖活动列表
     * @return array|string
     */
    public function getLotteryList()
    {
        try {
            return $this->app->activity->getAlByMachine();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 生成抽奖活动订单
     * @return array|string
     */
    public function getLotteryOrder()
    {
        try {
            return $this->app->activity->lotteryOrder();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 执行抽奖结果
     * @return array|string
     * @throws \Exception
     */
    public function getLuckyDraw()
    {
        try {
            return $this->app->activity->luckyDrawResult();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 抽奖订单出货
     * @return array|string
     * @throws \Exception
     */
    public function getLotteryOutGoods()
    {
        try {
            return $this->app->activity->lotteryOutGoods();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备满减满送活动信息
     * @return array|string
     */
    public function getFd()
    {
        try {
            return $this->app->activity->getFdByMachine();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 使用提货码
     * @return array|\think\response\Json
     */
    public function usePickCode()
    {
        try {
            $result = $this->app->activity->usePickCode();
            actionLog(@obj2arr($result), '使用提货码返回结果');
            return $result;
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 订单使用满减满送活动
     * @return mixed
     */
    public function useFd()
    {
        try {
            return $this->app->activity->useFd();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 订单使用优惠券
     * @return array|\think\response\Json
     */
    public function useCoupon()
    {
        try {
            return $this->app->activity->useCoupon();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取设备公网IP
     * @return array|string
     */
    public function getIp()
    {
        try {
            return $this->app->api->ip();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 未取事件上报
     * @return array|bool|string
     */
    public function unclaimed()
    {
        try {
            return $this->app->saleOrders->subUnclaimed();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 重置出厂设置
     * @return mixed
     */
    public function resetMachine()
    {
        try {
            return $this->app->api->reset();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取组合商品列表
     * @return array|\think\response\Json
     */
    public function getGoodsMultiple()
    {
        try {
            return $this->app->api->getGoodsMultiple();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 提交固定组合商品数据生成订单数据
     * @return array|\think\response\Json
     */
    public function subGoodsMultiple()
    {
        try {
            return $this->app->api->subGoodsMultipleOrder();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 设备退出H5微商城
     * @return array|bool|string
     */
    public function logoutH5()
    {
        try {
            return $this->app->api->logoutH5();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取订单小票
     * @return array|\think\response\Json
     */
    public function receipt()
    {
        try {
            return $this->app->api->receipt();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }


    /**
     * 上报回收箱信息
     * @return array|\think\response\Json
     */
    public function recycleBoxReport()
    {
        try {
            return $this->app->api->recycleBoxReport();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * HTTP心跳上报
     * @return array|string
     */
    public function httpHeartbeat()
    {
        try {
            return $this->app->api->httpHeartbeat();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 接收设备上传的首页截屏路径
     * @return array|string
     */
    public function reportScreenImg()
    {
        try {
            return $this->app->api->reportScreenImg();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 设备主动获取出货信息
     * @return array|string
     */
    public function requireOutGoods()
    {
        try {
            return $this->app->api->requireOutGoods();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

     /**
     * 设置设备http_out_status状态
     * @return array|string
     */
    public function setHttpOutStatus()
    {
        try {
            return $this->app->api->setHttpOutStatus();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * HTTP触发出货结果闭环（投递MQ，触发OutGoodsTrait::outGoods）
     * @return array|string
     */
    // public function triggerOutGoodsByHttp()
    // {
    //     try {
    //         return $this->app->api->triggerOutGoodsByHttp();
    //     } catch (\Exception $e) {
    //         actionException($e, 1);
    //         return returnTryCatch($e->getMessage());
    //     }
    // }

    /**
     * 获取订单支付状态
     * @return array|string
     */
    public function getOrderPayStatus()
    {
        try {
            return $this->app->api->getOrderPayStatus();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 取卡  卡添加积分   上传订单号、上传卡号
     * @return array|\think\response\Json
     */
    public function cardAddPoints()
    {
        try {
            $res = $this->app->api->cardAddPoints();
             if (isset($this->data['bind_id']) && !empty($this->data['bind_id'])) {
                $res = $this->app->api->cardBindWcuser();
            }
            return $res;
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

   

    /**
     * 取卡积分变化记录
     * @return array|\think\response\Json
     */
    public function getCardChangeLogs()
    {
        try {
            return $this->app->api->getCardChangeLogs();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 检查余额支付是否需要支付密码
     * @return array|\think\response\Json
     */
    public function checkBalancePayPassword()
    {
        try {
            return $this->app->api->checkBalancePayPassword();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

     /**
     * 获取微程短信验证码
     * @return array|\think\response\Json
     */
    public function getWcSmSCode()
    {
        try {
            return $this->app->api->getWcSmSCode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
    * 会员账号登录
    * @return array|\think\response\Json
    */
    public function wcLoginUser()
    {
        try {
            return $this->app->api->getWcLoginUser();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取当前设备最近两分钟内最后一条微程登录信息
     * @return array|\think\response\Json
     */
    public function getWcLatestLoginInfo()
    {
        try {
            return $this->app->api->getWcLatestLoginInfo();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
    * 会员同步积分
    * @return array|\think\response\Json
    */
    public function wcUserAddPoints()
    {
        try {
            return $this->app->api->setWcUserAddPoints();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
    * 生成积分二维码
    * @return array|\think\response\Json
    */
    public function wcPointsQrcode()
    {
        try {
            return $this->app->api->getWcPointsQrcode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

     /**
     * 创建会员卡支付订单
     * @return array|string
     * @throws \Exception
     */
    public function createdCardSaleOrder()
    {
        try {
            return $this->app->api->addCardSaleOrdersAndDetails();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取微程商品信息
     * @return array|string
     * @throws \Exception
     */
    public function getWcGoodsLists(){
        try {
            return $this->app->api->getWcGoodsLocalLists();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }


    /**
     * 新版获取微程商品信息
     * @return array|string
     * @throws \Exception
     */
    public function getWcMCLists(){
        try {
            return $this->app->api->getWcMCLists();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    public function getWcUserInfo(){
        try {
            return $this->app->api->getWcUserAddress();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    public function getLoginWcQrCode(){
        try {
            return $this->app->api->getLoginWcQrCode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    
    /**
     * 获取租赁设备所有组织的商品列表
     * @return array|string
     * @throws \Exception
     */
    public function getMachineRentOrgLists(){
        try {
            return $this->app->api->getMachineRentOrgLists();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }


    /**
     * 获取租赁设备所有组织的商品列表
     * @return array|string
     * @throws \Exception
     */
    public function getRentOrgGoodsLists(){
        try {
            return $this->app->api->getRentOrgGoodsLists();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 微程商品查询接口
     * @return array|string
     * @throws \Exception
     */
    public function searchWCGoods(){
        try {
            return $this->app->api->searchWCGoods();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取维护项目（按层级）
     * @return array|string
     */
    public function getMaintenanceItems()
    {
        try {
            return $this->app->api->getMaintenanceItems();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 提交维护记录
     * @return array|string
     */
    public function submitMaintenanceRecord()
    {
        try {
            return $this->app->api->submitMaintenanceRecord();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 从上传的文件内容生成 maintenance_records 的 INSERT SQL
     * @return array|string
     */
    public function importMaintenanceRecords()
    {
        try {
            return $this->app->api->importMaintenanceRecordsFromFile();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 从上传的文件内容生成并插入 check_list_records
     * @return array|string
     */
    public function importCheckListRecords()
    {
        try {
            return $this->app->api->importCheckListRecordsFromFile();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 查询维护记录（按records_code归类）
     * @return array|string
     */
    public function getMaintenanceRecords()
    {
        try {
            return $this->app->api->getMaintenanceRecords();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 提交客户退货日志
     * @return array|string
     */
    public function submitRefundGoodsLog()
    {
        try {
            return $this->app->api->submitRefundGoodsLog();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取检查清单项目（按层级）
     * @return array|string
     */
    public function getCheckListItems()
    {
        try {
            return $this->app->api->getCheckListItems();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 校验巡检人员账号是否存在
     * @return array|string
     */
    public function checkInspectionStaffCode()
    {
        try {
            return $this->app->api->checkInspectionStaffCode();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 提交检查清单记录
     * @return array|string
     */
    public function submitCheckListRecord()
    {
        try {
            return $this->app->api->submitCheckListRecord();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 查询检查清单记录（按records_code归类）
     * @return array|string
     */
    public function getCheckListRecords()
    {
        try {
            return $this->app->api->getCheckListRecords();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    public function test()
    {
        $this->app->api->test();
    }

    /**
     * http请求设备故障码上报接口
     * @return array|\think\response\Json
     */
    public function sendErro()
    {
        $postData = input();
        //$this->validate($postData, $this->validatePath . 'sendErro');
        try {
            // 用于本地联调：simulate_mq=1 时按 MQ 的消息结构模拟一次故障码上报
            if (!empty($postData['simulate_mq'])) {
                $mqData = [
                    "msg_id" => $postData['mq_msg_id'] ?? uniqid("mq_"),
                    "machine_id" => $postData['machine_id'],
                    "timestamp" => time(),
                    "data" => json_encode([
                        "msgType" => "errorCode",
                        "errorCode" => $postData['errorCode'] ?? "",
                        "msg" => $postData['msg'] ?? "",
                        "error_position" => $postData['error_position'] ?? "",
                    ], JSON_UNESCAPED_UNICODE),
                    "mac" => $this->request->header("mac") ?? "",
                ];
                $mqData['sign'] = $this->app->api->makeSign($mqData);
                $mqConfig = [
                    "machine_id" => $mqData['machine_id'],
                    "data" => $mqData,
                    "mac" => $mqData['mac'],
                ];
                $mqApp = AppFactory::machine($mqConfig);
                $mqResult = $mqApp->mq->onMessage();
                return returnState(200, '模拟MQ故障码上报完成', [
                    'mode' => 'mq',
                    'msg_id' => $mqData['msg_id'],
                    'result' => $mqResult,
                ]);
            }
            return $this->app->api->sendErro();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    
    /**
     * 获取设备主题配置
     * @return array|string
     */
    public function getTopicPage()
    {
        try {
            return $this->app->api->topicPage();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

	/**
     * 获取并同步设备校准页配置
     * @return array|string
     */
    public function getCalibrationConfig()
    {
        try {
            return $this->app->api->machineCalibrationConfig();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    
    /**
     * 设备上报每日物联卡流量使用
     * @return array|string
     */
    public function reportSimCardMachineUsage()
    {
        try {
            return $this->app->api->reportSimCardMachineUsage();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    
    /**
     * 设备通过 HTTP 上报物联卡信号
     * @return array|string
     */
    public function reportSimSignal()
    {
        try {
            $postData = input();
            $postData = json2arr($postData);
            $machineId = $postData['machine_id'] ?? '';
            $cacheKey = 'reportSimSignal_limit_' . $machineId;
            if ($machineId && cache($cacheKey)) {
                return returnState(300, '同一台设备2分钟内只允许一条信号上报');
            }
            if ($machineId) {
                cache($cacheKey, 1, 120);
            }
            $machine = $this->app->api->machine ?? [];
            $this->updateSimSignalWithData($machine, $postData);
            return returnState(200, lang('action_success'));
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 获取预补货详情（设备端）
     * @return array|string
     */
    public function getPreReplenishmentDetail()
    {
        try {
            return $this->app->api->getPreReplenishmentDetail();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }

    /**
     * 确认预补货（设备端）
     * @return array|string
     */
    public function confirmPreReplenishment()
    {
        try {
            return $this->app->api->confirmPreReplenishment();
        } catch (\Exception $e) {
            actionException($e, 1);
            return returnTryCatch($e->getMessage());
        }
    }
    
}
