<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2025/3/18
 * Time: 15:22
 */

namespace app\machine\controller;


use app\AppFactory\AppFactory;
use app\machine\validate\VRobot;

class Robot extends Common
{
    protected $validatePath = VRobot::class;
    protected $config;
    protected $noCheckApi = [];
    /**
     * 初始化
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        try {
            $postData = input();
            $postData = json2arr($postData);
            actionLog($postData,'接收到的数据');
            $action = $this->request->action();
            $reflection = new \ReflectionClass(__CLASS__);
            $methods = $reflection->getMethods();
            $methodNames = array_map(function ($method) {
                return $method->getName();
            },$methods);
            if (!in_array($action,$methodNames)) {
                returnState(300,lang("error_api"))->send();
                die();
            }
            $this->validate($postData,$this->validatePath . $action);
            $frequency = checkFrequency($action,1);
            if ($frequency !== true) {
                $frequency = obj2arr($frequency);
                returnState(300, $frequency)->send();
                die();
            }
            $mac = $this->request->header("mac");
            $this->config = [
                "machine_id" => $postData['machine_id'],
                "data" => $postData,
                "mac" => $mac
            ];
            $this->app = AppFactory::machine($this->config);
            if (!in_array($action, $this->noCheckApi) && $this->app->api->checkSign($postData) !== true) {
                @cache($postData['machine_id'] . ".signKey", null);
                returnState(100, lang("check_sign_fail"))->send();
                die();
            }
            $result = $this->app->robot->$action();
            $result->send();
        } catch (\Exception $e) {
            returnState(300, lang($e->getMessage()))->send();
            die();
        }
    }
}