<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/1/25
 * Time: 19:37
 */

namespace app\pay\controller;


use app\BaseController;

class Common extends BaseController
{

    protected $key; // cf20240123terminal

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->key = env("api.md5Key");
    }
}