<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2024/1/25
 * Time: 19:37
 */

namespace app\pay\controller;


use app\AppFactory\AppFactory;
use app\AppFactory\Pay\Application;
use think\facade\Lang;

class Payment extends Common
{
    /**
     * @var Application
     */
    protected $app;
    protected $validatePath = 'app\pay\validate\VSaleOrder.';
    protected $config;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $postData = input();
        $postData = json2arr($postData);
        actionLog($postData,'发起支付数据');
        if (!$postData) die(returnState(100,\lang("request_params_require"))->send());
        $action = $this->request->action();
        try { $this->validate($postData,$this->validatePath . $action);}
        catch (\Exception $e) { die(json_encode(['state' => 300, 'msg' => Lang::get($e->getMessage())],320));}
        $frequency = checkFrequency($action);
        if ($frequency !== true) {
            $frequency = obj2arr($frequency);
            die(json_encode($frequency,320));
        }
        $this->config = [
            "key" => $this->key,
            "data" => $postData,
        ];
        $this->app = AppFactory::pay($this->config);
    }

    /**
     * 订单支付
     * @return array|string
     */
    public function sale_order()
    {
        $result = $this->app->payment->orderPay();
        actionLog(@obj2arr($result) ?? "",'发起支付返回结果');
        return $result;
    }

    /**
     * 取消支付
     * @return array|string
     */
    public function cancel()
    {
        return $this->app->payment->cancelPay();
    }

    /**
     * 改密码
     * @return array|string
     */
    public function changePassword()
    {
        return $this->app->payment->changeCardPwd();
    }
}